
import type { Property, Agent, Testimonial, User } from './types';

const agents: Agent[] = [
  {
    id: '1',
    name: 'Alice Johnson',
    title: 'Senior Real Estate Agent',
    phone: '123-456-7890',
    email: 'alice.j@realestate.com',
    image: 'https://placehold.co/400x400.png',
    propertiesCount: 5,
    data_ai_hint: "professional woman"
  },
  {
    id: '2',
    name: 'Bob Williams',
    title: 'Commercial Property Specialist',
    phone: '123-456-7891',
    email: 'bob.w@realestate.com',
    image: 'https://placehold.co/400x400.png',
    propertiesCount: 3,
    data_ai_hint: "professional man"
  },
   {
    id: '3',
    name: 'Charlie Brown',
    title: 'Luxury Home Consultant',
    phone: '123-456-7892',
    email: 'charlie.b@realestate.com',
    image: 'https://placehold.co/400x400.png',
    propertiesCount: 4,
    data_ai_hint: "friendly man"
  },
];

const properties: Property[] = [
  {
    id: '1',
    title: 'Modern Downtown Loft',
    price: 1200000,
    address: '123 Main St, Anytown, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1500,
    image: '/images/properties/property-1.jpg',
    images: ['/images/properties/property-1-1.jpg', '/images/properties/property-1-2.jpg', '/images/properties/property-1-3.jpg'],
    featured: true,
    type: 'Apartment',
    description: 'A beautiful and spacious loft in the heart of the city. Features high ceilings, large windows, and a modern kitchen. Perfect for urban living.',
    amenities: ['Gym', 'Pool', 'Rooftop Deck', '24/7 Security'],
    agentId: '1',
    data_ai_hint: "modern apartment interior"
  },
  {
    id: '2',
    title: 'Suburban Family Home',
    price: 750000,
    address: '456 Oak Ave, Suburbia, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 2500,
    image: '/images/properties/property-2.jpg',
    images: ['/images/properties/property-2-1.jpg', '/images/properties/property-2-2.jpg', '/images/properties/property-2-3.jpg'],
    featured: true,
    type: 'House',
    description: 'A charming family home in a quiet suburban neighborhood. Features a large backyard, a two-car garage, and a newly renovated kitchen.',
    amenities: ['Backyard', 'Garage', 'Fireplace', 'Modern Kitchen'],
    agentId: '2',
    data_ai_hint: "suburban house exterior"
  },
  {
    id: '3',
    title: 'Luxury Beachfront Villa',
    price: 3500000,
    address: '789 Ocean Blvd, Beachtown, USA',
    bedrooms: 5,
    bathrooms: 6,
    area: 5000,
    image: '/images/properties/property-3.jpg',
    images: ['/images/properties/property-3-1.jpg', '/images/properties/property-3-2.jpg', '/images/properties/property-3-3.jpg'],
    featured: true,
    type: 'Villa',
    description: 'An exquisite beachfront villa with breathtaking ocean views. Features a private pool, direct beach access, and a home theater.',
    amenities: ['Private Pool', 'Beach Access', 'Home Theater', 'Gourmet Kitchen', 'Ocean View'],
    agentId: '3',
    data_ai_hint: "luxury villa beach"
  },
  {
    id: '4',
    title: 'Cozy Condo with City View',
    price: 550000,
    address: '101 Pine St, Anytown, USA',
    bedrooms: 1,
    bathrooms: 1,
    area: 800,
    image: '/images/properties/property-4.jpg',
    images: ['/images/properties/property-4-1.jpg', '/images/properties/property-4-2.jpg', '/images/properties/property-4-3.jpg'],
    featured: false,
    type: 'Condo',
    description: 'A cozy and modern condo with a stunning view of the city skyline. Perfect for a young professional or couple. Building includes a gym and pool.',
    amenities: ['Gym', 'Pool', 'Concierge', 'City View'],
    agentId: '1',
    data_ai_hint: "modern condo interior"
  },
  {
    id: '5',
    title: 'Spacious House with Garden',
    price: 850000,
    address: '222 Maple Dr, Suburbia, USA',
    bedrooms: 3,
    bathrooms: 2,
    area: 2200,
    image: '/images/properties/property-5.jpg',
    images: ['/images/properties/property-5-1.jpg', '/images/properties/property-5-2.jpg', '/images/properties/property-5-3.jpg'],
    featured: false,
    type: 'House',
    description: 'A spacious house with a beautiful garden and outdoor patio. Ideal for families who love the outdoors. Includes a large living room and a formal dining area.',
    amenities: ['Garden', 'Patio', 'Garage', 'Hardwood Floors'],
    agentId: '2',
    data_ai_hint: "house garden"
  },
  {
    id: '6',
    title: 'Penthouse with Rooftop Terrace',
    price: 2500000,
    address: '333 Sky High Rd, Anytown, USA',
    bedrooms: 3,
    bathrooms: 4,
    area: 3000,
    image: '/images/properties/property-6.jpg',
    images: ['/images/properties/property-6-1.jpg', '/images/properties/property-6-2.jpg', '/images/properties/property-6-3.jpg'],
    featured: true,
    type: 'Apartment',
    description: 'A stunning penthouse apartment with a private rooftop terrace offering 360-degree city views. Luxury finishes throughout.',
    amenities: ['Rooftop Terrace', 'Private Elevator', 'Concierge', ' panoramic views'],
    agentId: '3',
    data_ai_hint: "luxury penthouse interior"
  },
  {
    id: '7',
    title: 'Quaint Cottage in the Woods',
    price: 450000,
    address: '77 Forest Lane, Woodland, USA',
    bedrooms: 2,
    bathrooms: 1,
    area: 1200,
    image: '/images/properties/property-7.jpg',
    images: ['/images/properties/property-7-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A cozy cottage surrounded by nature. Perfect for a peaceful retreat. Features a stone fireplace and a large wooden deck.',
    amenities: ['Fireplace', 'Deck', 'Hiking Trails Access'],
    agentId: '1',
    data_ai_hint: 'cottage woods'
  },
  {
    id: '8',
    title: 'Sleek Urban Studio',
    price: 480000,
    address: '88 City Center, Metropolis, USA',
    bedrooms: 1,
    bathrooms: 1,
    area: 600,
    image: '/images/properties/property-8.jpg',
    images: ['/images/properties/property-8-1.jpg'],
    featured: true,
    type: 'Apartment',
    description: 'A stylish and efficient studio in a bustling urban center. Close to public transport and nightlife.',
    amenities: ['Modern Appliances', 'Walk-in Closet', 'Building Security'],
    agentId: '2',
    data_ai_hint: 'urban studio'
  },
  {
    id: '9',
    title: 'Historic Townhouse',
    price: 980000,
    address: '99 Old Town Rd, Historyville, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2200,
    image: '/images/properties/property-9.jpg',
    images: ['/images/properties/property-9-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A beautifully preserved townhouse with historic charm and modern updates. Features original hardwood floors and a private garden.',
    amenities: ['Private Garden', 'Historic Details', 'Renovated Kitchen'],
    agentId: '3',
    data_ai_hint: 'historic townhouse'
  },
  {
    id: '10',
    title: 'Mountain View Condo',
    price: 620000,
    address: '10 Mountain Pass, Summit, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1400,
    image: '/images/properties/property-10.jpg',
    images: ['/images/properties/property-10-1.jpg'],
    featured: true,
    type: 'Condo',
    description: 'A comfortable condo with stunning mountain views from every window. Includes access to a community lodge and ski slopes.',
    amenities: ['Mountain View', 'Ski-in/Ski-out', 'Community Hot Tub'],
    agentId: '1',
    data_ai_hint: 'mountain condo'
  },
  {
    id: '11',
    title: 'Riverside Family Retreat',
    price: 1100000,
    address: '111 Riverbend Dr, Riverton, USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 3200,
    image: '/images/properties/property-11.jpg',
    images: ['/images/properties/property-11-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A large family home on the river. Features a private dock, spacious lawn, and a game room.',
    amenities: ['River Access', 'Private Dock', 'Game Room'],
    agentId: '2',
    data_ai_hint: 'house river'
  },
  {
    id: '12',
    title: 'Eco-Friendly Modern Home',
    price: 1350000,
    address: '12 Solar Way, Greenville, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2800,
    image: '/images/properties/property-12.jpg',
    images: ['/images/properties/property-12-1.jpg'],
    featured: true,
    type: 'House',
    description: 'A state-of-the-art eco-friendly home with solar panels and sustainable materials. Designed for green living without sacrificing luxury.',
    amenities: ['Solar Panels', 'Rainwater Harvesting', 'Smart Home System'],
    agentId: '3',
    data_ai_hint: 'eco friendly house'
  },
  {
    id: '13',
    title: 'Artist Loft with Studio Space',
    price: 890000,
    address: '13 Creative Circle, Artstown, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 2000,
    image: '/images/properties/property-13.jpg',
    images: ['/images/properties/property-13-1.jpg'],
    featured: false,
    type: 'Apartment',
    description: 'A spacious loft with high ceilings and a dedicated studio space, perfect for artists and creatives.',
    amenities: ['Studio Space', 'High Ceilings', 'Natural Light'],
    agentId: '1',
    data_ai_hint: 'artist loft'
  },
  {
    id: '14',
    title: 'Downtown High-Rise Apartment',
    price: 1500000,
    address: '1400 Skyline Ave, Metropolis, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2100,
    image: '/images/properties/property-14.jpg',
    images: ['/images/properties/property-14-1.jpg'],
    featured: true,
    type: 'Apartment',
    description: 'A luxury apartment on a high floor with panoramic city views. Building has a pool, gym, and 24/7 concierge.',
    amenities: ['Panoramic Views', 'Floor-to-Ceiling Windows', 'Valet Parking'],
    agentId: '2',
    data_ai_hint: 'luxury apartment'
  },
  {
    id: '15',
    title: 'Ranch-Style Country House',
    price: 950000,
    address: '15 Prairie Lane, Countryside, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 3500,
    image: '/images/properties/property-15.jpg',
    images: ['/images/properties/property-15-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A sprawling ranch-style house on a large plot of land. Features horse stables and wide-open spaces.',
    amenities: ['Large Acreage', 'Horse Stables', 'Wraparound Porch'],
    agentId: '3',
    data_ai_hint: 'ranch house'
  },
  {
    id: '16',
    title: 'Lakeside Cabin',
    price: 680000,
    address: '16 Water\'s Edge, Laketown, USA',
    bedrooms: 3,
    bathrooms: 2,
    area: 1600,
    image: '/images/properties/property-16.jpg',
    images: ['/images/properties/property-16-1.jpg'],
    featured: true,
    type: 'House',
    description: 'A charming cabin with direct lake access. Perfect for fishing, boating, and summer getaways.',
    amenities: ['Lakefront', 'Private Dock', 'Screened Porch'],
    agentId: '1',
    data_ai_hint: 'lake cabin'
  },
  {
    id: '17',
    title: 'Chic Urban Condo',
    price: 720000,
    address: '17 Trendsetter Way, Anytown, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1300,
    image: '/images/properties/property-17.jpg',
    images: ['/images/properties/property-17-1.jpg'],
    featured: false,
    type: 'Condo',
    description: 'A very stylish condo in a trendy neighborhood, known for its boutiques and cafes. Features a balcony and designer finishes.',
    amenities: ['Balcony', 'Designer Finishes', 'Community Lounge'],
    agentId: '2',
    data_ai_hint: 'urban condo'
  },
  {
    id: '18',
    title: 'Mediterranean-Style Villa',
    price: 2800000,
    address: '18 Vineyard Valley, Wine Country, USA',
    bedrooms: 5,
    bathrooms: 5,
    area: 4500,
    image: '/images/properties/property-18.jpg',
    images: ['/images/properties/property-18-1.jpg'],
    featured: true,
    type: 'Villa',
    description: 'An elegant Mediterranean-style villa with a courtyard, fountain, and wine cellar. Set in a beautiful vineyard.',
    amenities: ['Courtyard', 'Wine Cellar', 'Swimming Pool'],
    agentId: '3',
    data_ai_hint: 'mediterranean villa'
  },
  {
    id: '19',
    title: 'Affordable Starter Home',
    price: 350000,
    address: '19 Opportunity Ave, Suburbia, USA',
    bedrooms: 3,
    bathrooms: 2,
    area: 1500,
    image: '/images/properties/property-19.jpg',
    images: ['/images/properties/property-19-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A perfect and affordable starter home for a new family. Features a fenced-in backyard and is close to schools.',
    amenities: ['Fenced Yard', 'Near Schools', 'Updated Appliances'],
    agentId: '1',
    data_ai_hint: 'starter home'
  },
  {
    id: '20',
    title: 'Industrial Loft Conversion',
    price: 1150000,
    address: '20 Factory Row, Anytown, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 2400,
    image: '/images/properties/property-20.jpg',
    images: ['/images/properties/property-20-1.jpg'],
    featured: false,
    type: 'Apartment',
    description: 'A unique loft in a converted factory. Features exposed brick, high ceilings, and industrial details.',
    amenities: ['Exposed Brick', 'High Ceilings', 'Freight Elevator Access'],
    agentId: '2',
    data_ai_hint: 'industrial loft'
  },
  {
    id: '21',
    title: 'Secluded Forest House',
    price: 880000,
    address: '21 Whisperwind Path, Forest, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 3000,
    image: '/images/properties/property-21.jpg',
    images: ['/images/properties/property-21-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A private and secluded home surrounded by dense forest. Perfect for nature lovers seeking tranquility.',
    amenities: ['Secluded', 'Forest Views', 'Hiking Trails'],
    agentId: '3',
    data_ai_hint: 'forest house'
  },
  {
    id: '22',
    title: 'Golf Course Estate',
    price: 4200000,
    address: '22 Fairway Drive, Greenside, USA',
    bedrooms: 6,
    bathrooms: 7,
    area: 7000,
    image: '/images/properties/property-22.jpg',
    images: ['/images/properties/property-22-1.jpg'],
    featured: true,
    type: 'House',
    description: 'An expansive estate on a prestigious golf course. Features a home gym, theater, and custom pool.',
    amenities: ['Golf Course View', 'Home Gym', 'Theater Room', 'Custom Pool'],
    agentId: '1',
    data_ai_hint: 'luxury house'
  },
  {
    id: '23',
    title: 'Bright and Airy Beach House',
    price: 1750000,
    address: '23 Sandy Lane, Beachtown, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2200,
    image: '/images/properties/property-23.jpg',
    images: ['/images/properties/property-23-1.jpg'],
    featured: true,
    type: 'House',
    description: 'A beautiful beach house with an open floor plan and plenty of natural light. Just steps from the sand.',
    amenities: ['Beach Access', 'Ocean View', 'Outdoor Shower'],
    agentId: '2',
    data_ai_hint: 'beach house'
  },
  {
    id: '24',
    title: 'Penthouse with Private Pool',
    price: 5500000,
    address: '24 Skyline Terrace, Metropolis, USA',
    bedrooms: 4,
    bathrooms: 5,
    area: 4800,
    image: '/images/properties/property-24.jpg',
    images: ['/images/properties/property-24-1.jpg'],
    featured: true,
    type: 'Apartment',
    description: 'The ultimate in luxury living. This penthouse features a private rooftop pool and unparalleled city views.',
    amenities: ['Private Pool', 'Rooftop Terrace', '360-degree Views', 'Private Chef Kitchen'],
    agentId: '3',
    data_ai_hint: 'luxury penthouse'
  },
  {
    id: '25',
    title: 'Suburban Tudor Home',
    price: 920000,
    address: '25 Tudor Grove, Suburbia, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 2700,
    image: '/images/properties/property-25.jpg',
    images: ['/images/properties/property-25-1.jpg'],
    featured: false,
    type: 'House',
    description: 'Classic Tudor style home with beautiful architectural details in a family-friendly neighborhood.',
    amenities: ['Landscaped Garden', 'Two-car garage', 'Classic Architecture'],
    agentId: '1',
    data_ai_hint: 'tudor house'
  },
  {
    id: '26',
    title: 'Minimalist City Apartment',
    price: 680000,
    address: '26 Simple Street, Anytown, USA',
    bedrooms: 2,
    bathrooms: 1,
    area: 1100,
    image: '/images/properties/property-26.jpg',
    images: ['/images/properties/property-26-1.jpg'],
    featured: false,
    type: 'Apartment',
    description: 'A minimalist apartment with clean lines and a focus on simplicity and function. Located in a quiet, yet central area.',
    amenities: ['Minimalist Design', 'Smart Storage', 'Quiet Street'],
    agentId: '2',
    data_ai_hint: 'minimalist apartment'
  },
  {
    id: '27',
    title: 'Desert Modern Home',
    price: 1950000,
    address: '27 Cactus Trail, Desert Springs, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 3200,
    image: '/images/properties/property-27.jpg',
    images: ['/images/properties/property-27-1.jpg'],
    featured: true,
    type: 'House',
    description: 'A stunning modern home in the desert, designed to blend with the landscape. Features a negative-edge pool and amazing sunset views.',
    amenities: ['Desert Landscape', 'Infinity Pool', 'Sunset Views'],
    agentId: '3',
    data_ai_hint: 'desert house'
  },
  {
    id: '28',
    title: 'Garden Apartment',
    price: 650000,
    address: '28 Blossom Court, Greenville, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1300,
    image: '/images/properties/property-28.jpg',
    images: ['/images/properties/property-28-1.jpg'],
    featured: false,
    type: 'Apartment',
    description: 'A lovely ground-floor apartment with a private garden patio. Perfect for those who want outdoor space in the city.',
    amenities: ['Private Garden', 'Ground Floor', 'Pet Friendly'],
    agentId: '1',
    data_ai_hint: 'garden apartment'
  },
  {
    id: '29',
    title: 'Victorian Mansion',
    price: 3200000,
    address: '29 Heritage Hill, Historyville, USA',
    bedrooms: 7,
    bathrooms: 8,
    area: 8000,
    image: '/images/properties/property-29.jpg',
    images: ['/images/properties/property-29-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A grand Victorian mansion, fully restored with meticulous attention to detail. Features a ballroom and servants quarters.',
    amenities: ['Historic Restoration', 'Ballroom', 'Large Estate'],
    agentId: '2',
    data_ai_hint: 'victorian mansion'
  },
  {
    id: '30',
    title: 'Modern Farmhouse',
    price: 1450000,
    address: '30 Country Road, Farmland, USA',
    bedrooms: 5,
    bathrooms: 4,
    area: 4000,
    image: '/images/properties/property-30.jpg',
    images: ['/images/properties/property-30-1.jpg'],
    featured: true,
    type: 'House',
    description: 'A new-build modern farmhouse with a classic look and all the modern amenities. Features a gourmet kitchen and a large front porch.',
    amenities: ['Modern Farmhouse Style', 'Gourmet Kitchen', 'Wraparound Porch'],
    agentId: '3',
    data_ai_hint: 'modern farmhouse'
  },
  {
    id: '31',
    title: 'Sky-High City Condo',
    price: 1800000,
    address: '31 Cloud Nine, Metropolis, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2500,
    image: '/images/properties/property-31.jpg',
    images: ['/images/properties/property-31-1.jpg'],
    featured: false,
    type: 'Condo',
    description: 'Live in the clouds in this stunning high-rise condo. Features incredible views and five-star building amenities.',
    amenities: ['High Floor', 'City Views', 'Rooftop Pool'],
    agentId: '1',
    data_ai_hint: 'city condo'
  },
  {
    id: '32',
    title: 'Craftsman Bungalow',
    price: 780000,
    address: '32 Arts & Crafts Way, Suburbia, USA',
    bedrooms: 3,
    bathrooms: 2,
    area: 1900,
    image: '/images/properties/property-32.jpg',
    images: ['/images/properties/property-32-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A charming Craftsman bungalow with a cozy fireplace and built-in cabinetry. A true gem in a quiet neighborhood.',
    amenities: ['Craftsman Style', 'Cozy Fireplace', 'Built-in Shelving'],
    agentId: '2',
    data_ai_hint: 'craftsman bungalow'
  },
  {
    id: '33',
    title: 'Waterfront Luxury Condo',
    price: 2100000,
    address: '33 Waterway, Beachtown, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2300,
    image: '/images/properties/property-33.jpg',
    images: ['/images/properties/property-33-1.jpg'],
    featured: true,
    type: 'Condo',
    description: 'A luxurious condo right on the water. Enjoy marina views from your private balcony. Building includes a private yacht club.',
    amenities: ['Waterfront', 'Marina View', 'Yacht Club Access'],
    agentId: '3',
    data_ai_hint: 'waterfront condo'
  },
  {
    id: '34',
    title: 'Sprawling Suburban Estate',
    price: 1900000,
    address: '34 Grandview Dr, Suburbia, USA',
    bedrooms: 5,
    bathrooms: 6,
    area: 5500,
    image: '/images/properties/property-34.jpg',
    images: ['/images/properties/property-34-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A large suburban estate with a pool, tennis court, and manicured gardens. Perfect for entertaining.',
    amenities: ['Swimming Pool', 'Tennis Court', 'Manicured Gardens'],
    agentId: '1',
    data_ai_hint: 'suburban estate'
  },
  {
    id: '35',
    title: 'Cozy Log Cabin',
    price: 550000,
    address: '35 Pine Cone Path, Woodland, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1400,
    image: '/images/properties/property-35.jpg',
    images: ['/images/properties/property-35-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A classic log cabin perfect for a mountain getaway. Features rustic decor and a wood-burning stove.',
    amenities: ['Log Cabin Construction', 'Wood-burning Stove', 'Mountain Setting'],
    agentId: '2',
    data_ai_hint: 'log cabin'
  },
  {
    id: '36',
    title: 'Contemporary Glass House',
    price: 3800000,
    address: '36 Crystal Clear, Modern Hills, USA',
    bedrooms: 4,
    bathrooms: 5,
    area: 4200,
    image: '/images/properties/property-36.jpg',
    images: ['/images/properties/property-36-1.jpg'],
    featured: true,
    type: 'House',
    description: 'A spectacular contemporary home made almost entirely of glass, offering seamless indoor-outdoor living.',
    amenities: ['Glass Walls', 'Indoor-Outdoor Living', 'Infinity Pool'],
    agentId: '3',
    data_ai_hint: 'modern glass house'
  },
  {
    id: '37',
    title: 'Duplex with Rental Income',
    price: 850000,
    address: '37 Two-Door Terrace, Anytown, USA',
    bedrooms: 4,
    bathrooms: 2,
    area: 2600,
    image: '/images/properties/property-37.jpg',
    images: ['/images/properties/property-37-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A fantastic investment opportunity. Live in one unit and rent out the other. Both units have been recently updated.',
    amenities: ['Rental Income', 'Separate Entrances', 'Updated Units'],
    agentId: '1',
    data_ai_hint: 'duplex house'
  },
  {
    id: '38',
    title: 'Urban Micro-Loft',
    price: 395000,
    address: '38 Compact Corner, Metropolis, USA',
    bedrooms: 0,
    bathrooms: 1,
    area: 450,
    image: '/images/properties/property-38.jpg',
    images: ['/images/properties/property-38-1.jpg'],
    featured: false,
    type: 'Apartment',
    description: 'A cleverly designed micro-loft that makes the most of its small footprint. Perfect for the urban minimalist.',
    amenities: ['Smart Design', 'Central Location', 'Low Maintenance'],
    agentId: '2',
    data_ai_hint: 'small apartment'
  },
  {
    id: '39',
    title: 'Classic Colonial Home',
    price: 1100000,
    address: '39 Independence Way, Historyville, USA',
    bedrooms: 5,
    bathrooms: 4,
    area: 3800,
    image: '/images/properties/property-39.jpg',
    images: ['/images/properties/property-39-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A beautiful Colonial home with a grand staircase and formal living and dining rooms. A timeless classic.',
    amenities: ['Colonial Architecture', 'Grand Staircase', 'Formal Dining Room'],
    agentId: '3',
    data_ai_hint: 'colonial house'
  },
  {
    id: '40',
    title: 'Ski Chalet',
    price: 1300000,
    address: '40 Snowflake Summit, Mountaintop, USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 3000,
    image: '/images/properties/property-40.jpg',
    images: ['/images/properties/property-40-1.jpg'],
    featured: true,
    type: 'House',
    description: 'A cozy and luxurious ski chalet with direct access to the slopes. Features a sauna and a large stone fireplace.',
    amenities: ['Ski-in/Ski-out', 'Sauna', 'Stone Fireplace'],
    agentId: '1',
    data_ai_hint: 'ski chalet'
  },
  {
    id: '41',
    title: 'Renovated Warehouse Loft',
    price: 1250000,
    address: '41 Industrial Way, Metropolis, USA',
    bedrooms: 3,
    bathrooms: 2,
    area: 2800,
    image: '/images/properties/property-41.jpg',
    images: ['/images/properties/property-41-1.jpg'],
    featured: false,
    type: 'Apartment',
    description: 'A stunning loft in a renovated warehouse with concrete floors, exposed ductwork, and a chef\'s kitchen.',
    amenities: ['Concrete Floors', 'Exposed Ductwork', 'Chef\'s Kitchen'],
    agentId: '2',
    data_ai_hint: 'warehouse loft'
  },
  {
    id: '42',
    title: 'Gated Community Villa',
    price: 2400000,
    address: '42 Secure Circle, Greenside, USA',
    bedrooms: 5,
    bathrooms: 5,
    area: 4600,
    image: '/images/properties/property-42.jpg',
    images: ['/images/properties/property-42-1.jpg'],
    featured: false,
    type: 'Villa',
    description: 'A beautiful villa in an exclusive gated community. Offers privacy, security, and access to community amenities.',
    amenities: ['Gated Community', '24/7 Security', 'Community Pool & Tennis'],
    agentId: '3',
    data_ai_hint: 'luxury villa'
  },
  {
    id: '43',
    title: 'Charming Cape Cod',
    price: 880000,
    address: '43 Seaside Street, Beachtown, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 2400,
    image: '/images/properties/property-43.jpg',
    images: ['/images/properties/property-43-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A classic Cape Cod style home with a charming garden, just a short walk from the beach.',
    amenities: ['Cape Cod Style', 'Walk to Beach', 'Charming Garden'],
    agentId: '1',
    data_ai_hint: 'cape cod house'
  },
  {
    id: '44',
    title: 'Downtown Live/Work Space',
    price: 950000,
    address: '44 Enterprise Esplanade, Anytown, USA',
    bedrooms: 1,
    bathrooms: 2,
    area: 2200,
    image: '/images/properties/property-44.jpg',
    images: ['/images/properties/property-44-1.jpg'],
    featured: false,
    type: 'Apartment',
    description: 'A flexible live/work space with a storefront and a modern apartment in the back. Perfect for entrepreneurs.',
    amenities: ['Live/Work Space', 'Storefront', 'Modern Apartment'],
    agentId: '2',
    data_ai_hint: 'live work space'
  },
  {
    id: '45',
    title: 'Hillside Home with Views',
    price: 1600000,
    address: '45 Overlook Trail, Hillside, USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 3500,
    image: '/images/properties/property-45.jpg',
    images: ['/images/properties/property-45-1.jpg'],
    featured: true,
    type: 'House',
    description: 'A stunning home built into a hillside, with panoramic views of the city and valley below.',
    amenities: ['Panoramic Views', 'Hillside Location', 'Multi-level Decks'],
    agentId: '3',
    data_ai_hint: 'hillside house'
  },
  {
    id: '46',
    title: 'Elegant Pre-War Apartment',
    price: 1400000,
    address: '46 Classic Avenue, Metropolis, USA',
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    image: '/images/properties/property-46.jpg',
    images: ['/images/properties/property-46-1.jpg'],
    featured: false,
    type: 'Apartment',
    description: 'An elegant apartment in a pre-war building, featuring high ceilings, crown molding, and a formal dining room.',
    amenities: ['Pre-War Building', 'High Ceilings', 'Crown Molding'],
    agentId: '1',
    data_ai_hint: 'classic apartment'
  },
  {
    id: '47',
    title: 'Countryside Barn Conversion',
    price: 1350000,
    address: '47 Haybale Way, Countryside, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 3200,
    image: '/images/properties/property-47.jpg',
    images: ['/images/properties/property-47-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A unique and spacious home that was once a barn. Features soaring ceilings and rustic wood beams.',
    amenities: ['Barn Conversion', 'Soaring Ceilings', 'Wood Beams'],
    agentId: '2',
    data_ai_hint: 'barn house'
  },
  {
    id: '48',
    title: 'Mid-Century Modern Gem',
    price: 1700000,
    address: '48 Retro Road, Suburbia, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    image: '/images/properties/property-48.jpg',
    images: ['/images/properties/property-48-1.jpg'],
    featured: true,
    type: 'House',
    description: 'A perfectly preserved mid-century modern home, with clean lines, large windows, and an open floor plan.',
    amenities: ['Mid-Century Modern', 'Open Floor Plan', 'Large Windows'],
    agentId: '3',
    data_ai_hint: 'mid century house'
  },
  {
    id: '49',
    title: 'Rooftop Garden Condo',
    price: 980000,
    address: '49 Green Top, Anytown, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1500,
    image: '/images/properties/property-49.jpg',
    images: ['/images/properties/property-49-1.jpg'],
    featured: false,
    type: 'Condo',
    description: 'A beautiful condo with access to a shared rooftop garden, offering a green oasis in the city.',
    amenities: ['Rooftop Garden', 'City Views', 'Community Grills'],
    agentId: '1',
    data_ai_hint: 'rooftop garden'
  },
  {
    id: '50',
    title: 'Luxury Townhouse with Elevator',
    price: 2200000,
    address: '50 Uptown Terrace, Metropolis, USA',
    bedrooms: 4,
    bathrooms: 5,
    area: 3800,
    image: '/images/properties/property-50.jpg',
    images: ['/images/properties/property-50-1.jpg'],
    featured: false,
    type: 'House',
    description: 'An elegant townhouse with a private elevator, gourmet kitchen, and rooftop deck.',
    amenities: ['Private Elevator', 'Rooftop Deck', 'Gourmet Kitchen'],
    agentId: '2',
    data_ai_hint: 'luxury townhouse'
  },
  {
    id: '51',
    title: 'Upstate NY Lake House',
    price: 2100000,
    address: '101 Finger Lakes, New York, USA',
    bedrooms: 5,
    bathrooms: 4,
    area: 4000,
    image: '/images/properties/property-51.jpg',
    images: ['/images/properties/property-51-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A beautiful lake house with a private dock and stunning water views.',
    amenities: ['Lakefront', 'Private Dock', 'Wine Cellar', 'Fire Pit'],
    agentId: '2',
    data_ai_hint: 'lake house'
  },
  {
    id: '52',
    title: 'Brooklyn Brownstone',
    price: 4200000,
    address: '102 Park Slope, Brooklyn, USA',
    bedrooms: 5,
    bathrooms: 4,
    area: 3800,
    image: '/images/properties/property-52.jpg',
    images: ['/images/properties/property-52-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A renovated brownstone in Park Slope with original details and a modern kitchen.',
    amenities: ['Original Details', 'Modern Kitchen', 'Garden', 'Roof Deck'],
    agentId: '3',
    data_ai_hint: 'brooklyn brownstone'
  },
  {
    id: '53',
    title: 'Greenwich CT Grand Estate',
    price: 14500000,
    address: '103 Round Hill, Greenwich, USA',
    bedrooms: 7,
    bathrooms: 10,
    area: 13000,
    image: '/images/properties/property-53.jpg',
    images: ['/images/properties/property-53-1.jpg'],
    featured: true,
    type: 'House',
    description: 'A stately brick Georgian on a private lane with a pool, tennis court, and guest house.',
    amenities: ['Pool', 'Tennis Court', 'Guest House', 'Formal Gardens'],
    agentId: '1',
    data_ai_hint: 'georgian estate'
  },
  {
    id: '54',
    title: 'Cambridge Historic Home',
    price: 3900000,
    address: '104 Brattle Street, Cambridge, USA',
    bedrooms: 6,
    bathrooms: 5,
    area: 5200,
    image: '/images/properties/property-54.jpg',
    images: ['/images/properties/property-54-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A significant historic home near Harvard Square with a large yard and carriage house.',
    amenities: ['Historic', 'Carriage House', 'Large Yard', 'Library'],
    agentId: '2',
    data_ai_hint: 'historic home'
  },
  {
    id: '55',
    title: 'New Mexico Adobe Home',
    price: 1600000,
    address: '105 Canyon Road, Santa Fe, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 3000,
    image: '/images/properties/property-55.jpg',
    images: ['/images/properties/property-55-1.jpg'],
    featured: false,
    type: 'House',
    description: 'An authentic adobe home with kiva fireplaces, vigas, and a private courtyard.',
    amenities: ['Adobe Construction', 'Kiva Fireplaces', 'Courtyard', 'Mountain Views'],
    agentId: '3',
    data_ai_hint: 'adobe home'
  },
  {
    id: '56',
    title: 'Florida Keys Private Island',
    price: 25000000,
    address: '106 Paradise Cay, Florida Keys, USA',
    bedrooms: 10,
    bathrooms: 12,
    area: 15000,
    image: '/images/properties/property-56.jpg',
    images: ['/images/properties/property-56-1.jpg'],
    featured: true,
    type: 'Villa',
    description: 'Your own private island with a main residence, guest villas, and a deep water marina.',
    amenities: ['Private Island', 'Deep Water Marina', 'Heli-Pad', 'Staff Quarters'],
    agentId: '1',
    data_ai_hint: 'private island'
  },
  {
    id: '57',
    title: 'San Francisco Victorian',
    price: 4500000,
    address: '69 Alamo Square, San Francisco, USA',
    bedrooms: 5,
    bathrooms: 4,
    area: 3800,
    image: '/images/properties/property-57.jpg',
    images: ['/images/properties/property-57-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A classic "Painted Lady" Victorian with views of Alamo Square Park.',
    amenities: ['Historic Home', 'City Views', 'Modern Kitchen'],
    agentId: '3',
    data_ai_hint: 'victorian house'
  },
  {
    id: '58',
    title: 'Napa Valley Vineyard Estate',
    price: 11000000,
    address: '70 Grapevine Rd, Napa, USA',
    bedrooms: 7,
    bathrooms: 8,
    area: 10000,
    image: '/images/properties/property-58.jpg',
    images: ['/images/properties/property-58-1.jpg'],
    featured: true,
    type: 'House',
    description: 'A sprawling estate with its own vineyard, wine cave, and luxury amenities.',
    amenities: ['Vineyard', 'Wine Cave', 'Tennis Court', 'Guest House'],
    agentId: '1',
    data_ai_hint: 'vineyard estate'
  },
  {
    id: '59',
    title: 'Sonoma Farmhouse',
    price: 3800000,
    address: '71 County Line, Sonoma, USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 3500,
    image: '/images/properties/property-59.jpg',
    images: ['/images/properties/property-59-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A beautiful modern farmhouse with a guest barn and pool.',
    amenities: ['Pool', 'Guest Barn', 'Vegetable Garden'],
    agentId: '2',
    data_ai_hint: 'modern farmhouse'
  },
  {
    id: '60',
    title: 'Lake Tahoe Lakefront',
    price: 9500000,
    address: '72 Emerald Bay, Lake Tahoe, USA',
    bedrooms: 6,
    bathrooms: 7,
    area: 6500,
    image: '/images/properties/property-60.jpg',
    images: ['/images/properties/property-60-1.jpg'],
    featured: true,
    type: 'House',
    description: 'A magnificent lakefront estate on the shores of Lake Tahoe with a private pier.',
    amenities: ['Lakefront', 'Private Pier', 'Home Theater', 'Sauna'],
    agentId: '3',
    data_ai_hint: 'lakefront mansion'
  },
  {
    id: '61',
    title: 'Pacific Heights Mansion',
    price: 18000000,
    address: '73 Billionaire Row, San Francisco, USA',
    bedrooms: 8,
    bathrooms: 10,
    area: 12000,
    image: '/images/properties/property-61.jpg',
    images: ['/images/properties/property-61-1.jpg'],
    featured: true,
    type: 'House',
    description: 'An elegant mansion in Pacific Heights with Golden Gate Bridge views.',
    amenities: ['Golden Gate Views', 'Ballroom', 'Indoor Pool', 'Staff Quarters'],
    agentId: '1',
    data_ai_hint: 'classic mansion'
  },
  {
    id: '62',
    title: 'Sausalito Houseboat',
    price: 1200000,
    address: '74 Waldo Point, Sausalito, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1500,
    image: '/images/properties/property-62.jpg',
    images: ['/images/properties/property-62-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A unique and artistic houseboat with stunning bay views.',
    amenities: ['Bay Views', 'Unique Architecture', 'Waterfront Living'],
    agentId: '2',
    data_ai_hint: 'houseboat interior'
  },
  {
    id: '63',
    title: 'Aspen Ski-In/Ski-Out',
    price: 15000000,
    address: '75 Aspen Mountain, Aspen, USA',
    bedrooms: 7,
    bathrooms: 9,
    area: 9000,
    image: '/images/properties/property-63.jpg',
    images: ['/images/properties/property-63-1.jpg'],
    featured: true,
    type: 'House',
    description: 'A luxurious ski-in/ski-out estate with a bowling alley and indoor spa.',
    amenities: ['Ski-In/Ski-Out', 'Bowling Alley', 'Indoor Spa', 'Mountain Views'],
    agentId: '3',
    data_ai_hint: 'luxury ski chalet'
  },
  {
    id: '64',
    title: 'Miami Beach Penthouse',
    price: 10500000,
    address: '76 South Beach, Miami, USA',
    bedrooms: 5,
    bathrooms: 6,
    area: 6000,
    image: '/images/properties/property-64.jpg',
    images: ['/images/properties/property-64-1.jpg'],
    featured: true,
    type: 'Condo',
    description: 'A stunning penthouse with a private rooftop pool and 360-degree ocean views.',
    amenities: ['Rooftop Pool', 'Ocean Views', 'Private Elevator', '24/7 Concierge'],
    agentId: '1',
    data_ai_hint: 'miami penthouse'
  },
  {
    id: '65',
    title: 'Austin Modern Farmhouse',
    price: 2500000,
    address: '77 South Congress, Austin, USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 3800,
    image: '/images/properties/property-65.jpg',
    images: ['/images/properties/property-65-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A chic modern farmhouse in the heart of Austin\'s trendiest neighborhood.',
    amenities: ['Pool', 'Outdoor Kitchen', 'Walk to shops'],
    agentId: '2',
    data_ai_hint: 'modern farmhouse'
  },
  {
    id: '66',
    title: 'NYC Soho Loft',
    price: 7800000,
    address: '78 Mercer Street, New York, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 3500,
    image: '/images/properties/property-66.jpg',
    images: ['/images/properties/property-66-1.jpg'],
    featured: false,
    type: 'Apartment',
    description: 'A classic cast-iron loft in Soho with high ceilings and a private keyed elevator.',
    amenities: ['Keyed Elevator', 'High Ceilings', 'Exposed Brick'],
    agentId: '3',
    data_ai_hint: 'soho loft'
  },
  {
    id: '67',
    title: 'Hamptons Beach House',
    price: 9200000,
    address: '79 Dune Road, The Hamptons, USA',
    bedrooms: 6,
    bathrooms: 7,
    area: 5200,
    image: '/images/properties/property-67.jpg',
    images: ['/images/properties/property-67-1.jpg'],
    featured: true,
    type: 'House',
    description: 'A beautiful oceanfront beach house with a pool, tennis court, and private beach access.',
    amenities: ['Oceanfront', 'Pool', 'Tennis Court', 'Private Beach'],
    agentId: '1',
    data_ai_hint: 'hamptons house'
  },
  {
    id: '68',
    title: 'Seattle Waterfront Home',
    price: 4800000,
    address: '80 Lake Washington, Seattle, USA',
    bedrooms: 5,
    bathrooms: 5,
    area: 4500,
    image: '/images/properties/property-68.jpg',
    images: ['/images/properties/property-68-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A contemporary waterfront home with a private dock and views of the city skyline.',
    amenities: ['Waterfront', 'Private Dock', 'City Views', 'Wine Cellar'],
    agentId: '2',
    data_ai_hint: 'seattle waterfront'
  },
  {
    id: '69',
    title: 'Boston Brownstone',
    price: 6500000,
    address: '81 Beacon Street, Boston, USA',
    bedrooms: 5,
    bathrooms: 6,
    area: 5000,
    image: '/images/properties/property-69.jpg',
    images: ['/images/properties/property-69-1.jpg'],
    featured: false,
    type: 'House',
    description: 'An elegant brownstone on a picturesque street in Beacon Hill.',
    amenities: ['Historic', 'Rooftop Deck', 'Garden', 'Au Pair Suite'],
    agentId: '3',
    data_ai_hint: 'boston brownstone'
  },
  {
    id: '70',
    title: 'Chicago Gold Coast Condo',
    price: 3800000,
    address: '82 Lake Shore Drive, Chicago, USA',
    bedrooms: 3,
    bathrooms: 4,
    area: 3200,
    image: '/images/properties/property-70.jpg',
    images: ['/images/properties/property-70-1.jpg'],
    featured: true,
    type: 'Condo',
    description: 'A luxury condo with stunning lake views and high-end finishes.',
    amenities: ['Lake Views', 'Valet Parking', 'Indoor Pool', 'Fitness Center'],
    agentId: '1',
    data_ai_hint: 'chicago condo'
  },
  {
    id: '71',
    title: 'Scottsdale Golf Estate',
    price: 5200000,
    address: '83 Whisper Rock, Scottsdale, USA',
    bedrooms: 5,
    bathrooms: 6,
    area: 6500,
    image: '/images/properties/property-71.jpg',
    images: ['/images/properties/property-71-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A custom estate on a private golf course with a resort-style backyard.',
    amenities: ['Golf Course', 'Resort Pool', 'Home Theater', 'Casita'],
    agentId: '2',
    data_ai_hint: 'scottsdale mansion'
  },
  {
    id: '72',
    title: 'Hawaiian Oceanfront Villa',
    price: 12000000,
    address: '84 North Shore, Oahu, USA',
    bedrooms: 6,
    bathrooms: 7,
    area: 7500,
    image: '/images/properties/property-72.jpg',
    images: ['/images/properties/property-72-1.jpg'],
    featured: true,
    type: 'Villa',
    description: 'A breathtaking oceanfront villa with direct beach access and an infinity pool.',
    amenities: ['Oceanfront', 'Infinity Pool', 'Tropical Gardens', 'Gourmet Kitchen'],
    agentId: '3',
    data_ai_hint: 'hawaii villa'
  },
  {
    id: '73',
    title: 'Montana Ranch',
    price: 7500000,
    address: '85 Big Sky, Montana, USA',
    bedrooms: 8,
    bathrooms: 10,
    area: 12000,
    image: '/images/properties/property-73.jpg',
    images: ['/images/properties/property-73-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A massive luxury ranch on hundreds of acres with a main lodge and guest cabins.',
    amenities: ['Acreage', 'Horse Stables', 'Fishing Pond', 'Mountain Views'],
    agentId: '1',
    data_ai_hint: 'luxury ranch'
  },
  {
    id: '74',
    title: 'Key West Conch House',
    price: 2200000,
    address: '86 Duval Street, Key West, USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 2800,
    image: '/images/properties/property-74.jpg',
    images: ['/images/properties/property-74-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A historic Conch-style house with a pool and lush tropical gardens.',
    amenities: ['Pool', 'Tropical Garden', 'Historic District', 'Guest Cottage'],
    agentId: '2',
    data_ai_hint: 'key west house'
  },
  {
    id: '75',
    title: 'New Orleans French Quarter',
    price: 3100000,
    address: '87 Royal Street, New Orleans, USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 3500,
    image: '/images/properties/property-75.jpg',
    images: ['/images/properties/property-75-1.jpg'],
    featured: false,
    type: 'House',
    description: 'An elegant townhouse with a private courtyard in the heart of the French Quarter.',
    amenities: ['Courtyard', 'Balconies', 'Historic', 'Gourmet Kitchen'],
    agentId: '3',
    data_ai_hint: 'new orleans townhouse'
  },
  {
    id: '76',
    title: 'Las Vegas Penthouse',
    price: 6800000,
    address: '88 The Strip, Las Vegas, USA',
    bedrooms: 4,
    bathrooms: 5,
    area: 5500,
    image: '/images/properties/property-76.jpg',
    images: ['/images/properties/property-76-1.jpg'],
    featured: true,
    type: 'Condo',
    description: 'A spectacular penthouse with panoramic views of the Las Vegas Strip.',
    amenities: ['Strip Views', 'Rooftop Pool', '24/7 Butler Service', 'Screening Room'],
    agentId: '1',
    data_ai_hint: 'vegas penthouse'
  },
  {
    id: '77',
    title: 'Portland Craftsman',
    price: 1300000,
    address: '89 NW 23rd, Portland, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 3100,
    image: '/images/properties/property-77.jpg',
    images: ['/images/properties/property-77-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A beautifully restored Craftsman home in a vibrant, walkable neighborhood.',
    amenities: ['Restored Woodwork', 'Walkable', 'Finished Basement', 'Garden'],
    agentId: '2',
    data_ai_hint: 'portland house'
  },
  {
    id: '78',
    title: 'Charleston Single House',
    price: 2800000,
    address: '90 South of Broad, Charleston, USA',
    bedrooms: 5,
    bathrooms: 5,
    area: 4200,
    image: '/images/properties/property-78.jpg',
    images: ['/images/properties/property-78-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A grand historic single house with double piazzas and a walled garden.',
    amenities: ['Piazzas', 'Walled Garden', 'Historic', 'Guest Suite'],
    agentId: '3',
    data_ai_hint: 'charleston house'
  },
  {
    id: '79',
    title: 'Nashville Music Row Home',
    price: 1900000,
    address: '91 Music Square, Nashville, USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 3600,
    image: '/images/properties/property-79.jpg',
    images: ['/images/properties/property-79-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A contemporary home with a recording studio near Music Row.',
    amenities: ['Recording Studio', 'Rooftop Deck', 'Modern Design'],
    agentId: '1',
    data_ai_hint: 'nashville home'
  },
  {
    id: '80',
    title: 'Savannah Historic District',
    price: 2400000,
    address: '92 Forsyth Park, Savannah, USA',
    bedrooms: 5,
    bathrooms: 5,
    area: 4500,
    image: '/images/properties/property-80.jpg',
    images: ['/images/properties/property-80-1.jpg'],
    featured: false,
    type: 'House',
    description: 'An elegant townhouse overlooking Forsyth Park with a carriage house.',
    amenities: ['Park View', 'Carriage House', 'Courtyard Garden', 'Historic'],
    agentId: '2',
    data_ai_hint: 'savannah house'
  },
  {
    id: '81',
    title: 'Texas Hill Country Ranch',
    price: 4800000,
    address: '93 Lone Star Trail, Hill Country, USA',
    bedrooms: 6,
    bathrooms: 7,
    area: 8000,
    image: '/images/properties/property-81.jpg',
    images: ['/images/properties/property-81-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A sprawling ranch with a custom home, pool, and guest lodge on 100 acres.',
    amenities: ['100 Acres', 'Pool', 'Guest Lodge', 'Horse Barn'],
    agentId: '3',
    data_ai_hint: 'texas ranch'
  },
  {
    id: '82',
    title: 'Washington D.C. Rowhouse',
    price: 3200000,
    address: '94 Capitol Hill, Washington D.C., USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 3200,
    image: '/images/properties/property-82.jpg',
    images: ['/images/properties/property-82-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A beautifully renovated Federal rowhouse on Capitol Hill.',
    amenities: ['Renovated', 'Rooftop Deck', 'English Basement', 'Historic'],
    agentId: '1',
    data_ai_hint: 'dc rowhouse'
  },
  {
    id: '83',
    title: 'Philadelphia Trinity House',
    price: 850000,
    address: '95 Elfreth\'s Alley, Philadelphia, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    image: '/images/properties/property-83.jpg',
    images: ['/images/properties/property-83-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A charming and historic Trinity house on America\'s oldest residential street.',
    amenities: ['Historic', 'Spiral Staircase', 'Cobblestone Street'],
    agentId: '2',
    data_ai_hint: 'historic house'
  },
  {
    id: '84',
    title: 'Salt Lake City Mountain Home',
    price: 2900000,
    address: '96 Wasatch Blvd, Salt Lake City, USA',
    bedrooms: 5,
    bathrooms: 5,
    area: 5500,
    image: '/images/properties/property-84.jpg',
    images: ['/images/properties/property-84-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A modern mountain home with panoramic views of the valley and mountains.',
    amenities: ['Valley Views', 'Mountain Views', 'Home Gym', 'Theater'],
    agentId: '3',
    data_ai_hint: 'mountain modern'
  },
  {
    id: '85',
    title: 'Atlanta Buckhead Estate',
    price: 8900000,
    address: '97 Tuxedo Park, Atlanta, USA',
    bedrooms: 7,
    bathrooms: 9,
    area: 11000,
    image: '/images/properties/property-85.jpg',
    images: ['/images/properties/property-85-1.jpg'],
    featured: true,
    type: 'House',
    description: 'A grand estate in the heart of Buckhead with a pool, tennis court, and formal gardens.',
    amenities: ['Pool', 'Tennis Court', 'Formal Gardens', 'Guest House'],
    agentId: '1',
    data_ai_hint: 'luxury estate'
  },
  {
    id: '86',
    title: 'Denver LoHi Duplex',
    price: 1500000,
    address: '98 Platte Street, Denver, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2600,
    image: '/images/properties/property-86.jpg',
    images: ['/images/properties/property-86-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A stylish duplex with a rooftop deck and city views in the Lower Highlands.',
    amenities: ['Rooftop Deck', 'City Views', 'Modern Finishes', 'Walkable'],
    agentId: '2',
    data_ai_hint: 'modern duplex'
  },
  {
    id: '87',
    title: 'Rural Vermont Farmhouse',
    price: 1200000,
    address: '99 Green Mountain, Vermont, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 3500,
    image: '/images/properties/property-87.jpg',
    images: ['/images/properties/property-87-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A classic farmhouse on 50 acres with a large barn and rolling hills.',
    amenities: ['50 Acres', 'Barn', 'Mountain Views', 'Fireplace'],
    agentId: '3',
    data_ai_hint: 'vermont farmhouse'
  },
  {
    id: '88',
    title: 'Maine Coastal Compound',
    price: 5800000,
    address: '100 Ocean Point, Kennebunkport, USA',
    bedrooms: 8,
    bathrooms: 9,
    area: 9000,
    image: '/images/properties/property-88.jpg',
    images: ['/images/properties/property-88-1.jpg'],
    featured: true,
    type: 'House',
    description: 'A magnificent coastal compound with a main house, guest house, and deep water dock.',
    amenities: ['Oceanfront', 'Deep Water Dock', 'Guest House', 'Pool'],
    agentId: '1',
    data_ai_hint: 'coastal estate'
  },
  {
    id: '89',
    title: 'Dallas Modern Masterpiece',
    price: 7200000,
    address: '101 Preston Hollow, Dallas, USA',
    bedrooms: 6,
    bathrooms: 8,
    area: 10500,
    image: '/images/properties/property-89.jpg',
    images: ['/images/properties/property-89-1.jpg'],
    featured: true,
    type: 'House',
    description: 'An architectural marvel with clean lines, walls of glass, and a resort-style pool.',
    amenities: ['Architectural Design', 'Resort Pool', 'Home Gym', 'Media Room'],
    agentId: '2',
    data_ai_hint: 'modern mansion'
  },
  {
    id: '90',
    title: 'Houston River Oaks Estate',
    price: 9500000,
    address: '102 River Oaks Blvd, Houston, USA',
    bedrooms: 7,
    bathrooms: 9,
    area: 12000,
    image: '/images/properties/property-90.jpg',
    images: ['/images/properties/property-90-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A grand estate in a prestigious neighborhood with a tennis court and guest house.',
    amenities: ['Tennis Court', 'Guest House', 'Summer Kitchen', 'Formal Gardens'],
    agentId: '3',
    data_ai_hint: 'classic estate'
  },
  {
    id: '91',
    title: 'Boise Foothills Contemporary',
    price: 1800000,
    address: '103 Table Rock, Boise, USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 4200,
    image: '/images/properties/property-91.jpg',
    images: ['/images/properties/property-91-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A modern home nestled in the foothills with stunning valley and city views.',
    amenities: ['City Views', 'Valley Views', 'Hiking Trails', 'Modern Design'],
    agentId: '1',
    data_ai_hint: 'modern mountain home'
  },
  {
    id: '92',
    title: 'Sun Valley Ski Lodge',
    price: 6500000,
    address: '104 Bald Mountain, Sun Valley, USA',
    bedrooms: 6,
    bathrooms: 7,
    area: 7000,
    image: '/images/properties/property-92.jpg',
    images: ['/images/properties/property-92-1.jpg'],
    featured: true,
    type: 'House',
    description: 'A custom log and stone ski lodge with ski-in/ski-out access and a home theater.',
    amenities: ['Ski-In/Ski-Out', 'Home Theater', 'Sauna', 'Hot Tub'],
    agentId: '2',
    data_ai_hint: 'ski lodge'
  },
  {
    id: '93',
    title: 'Jackson Hole Ranch',
    price: 18000000,
    address: '105 Teton Village, Jackson Hole, USA',
    bedrooms: 8,
    bathrooms: 10,
    area: 11000,
    image: '/images/properties/property-93.jpg',
    images: ['/images/properties/property-93-1.jpg'],
    featured: true,
    type: 'House',
    description: 'A spectacular ranch with breathtaking Teton views, a guest lodge, and equestrian facilities.',
    amenities: ['Teton Views', 'Equestrian Facilities', 'Guest Lodge', 'Private Pond'],
    agentId: '3',
    data_ai_hint: 'wyoming ranch'
  },
  {
    id: '94',
    title: 'Santa Barbara Mission Canyon',
    price: 4200000,
    address: '106 Mission Canyon, Santa Barbara, USA',
    bedrooms: 5,
    bathrooms: 5,
    area: 4800,
    image: '/images/properties/property-94.jpg',
    images: ['/images/properties/property-94-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A serene retreat in Mission Canyon with ocean and mountain views.',
    amenities: ['Ocean Views', 'Mountain Views', 'Pool', 'Guest Suite'],
    agentId: '1',
    data_ai_hint: 'spanish style home'
  },
  {
    id: '95',
    title: 'Carmel-by-the-Sea Cottage',
    price: 3500000,
    address: '107 Scenic Road, Carmel, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2200,
    image: '/images/properties/property-95.jpg',
    images: ['/images/properties/property-95-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A storybook cottage with ocean views, just a short walk to the beach and village.',
    amenities: ['Ocean Views', 'Walk to Village', 'English Garden', 'Stone Fireplace'],
    agentId: '2',
    data_ai_hint: 'storybook cottage'
  },
  {
    id: '96',
    title: 'Pebble Beach Golf Estate',
    price: 22000000,
    address: '108 17-Mile Drive, Pebble Beach, USA',
    bedrooms: 7,
    bathrooms: 9,
    area: 11000,
    image: '/images/properties/property-96.jpg',
    images: ['/images/properties/property-96-1.jpg'],
    featured: true,
    type: 'House',
    description: 'A landmark estate on the 18th hole of Pebble Beach with unparalleled ocean views.',
    amenities: ['Ocean Views', 'Golf Course Frontage', 'Home Cinema', 'Wine Cellar'],
    agentId: '3',
    data_ai_hint: 'golf course mansion'
  },
  {
    id: '97',
    title: 'Big Sur Coastal Retreat',
    price: 8900000,
    address: '109 Highway 1, Big Sur, USA',
    bedrooms: 4,
    bathrooms: 5,
    area: 4500,
    image: '/images/properties/property-97.jpg',
    images: ['/images/properties/property-97-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A modern architectural home perched on the cliffs of Big Sur with dramatic ocean views.',
    amenities: ['Ocean Views', 'Clifftop', 'Infinity Pool', 'Modern Architecture'],
    agentId: '1',
    data_ai_hint: 'cliff house'
  },
  {
    id: '98',
    title: 'Manhattan UES Townhouse',
    price: 28000000,
    address: '110 East 70th, New York, USA',
    bedrooms: 6,
    bathrooms: 8,
    area: 9000,
    image: '/images/properties/property-98.jpg',
    images: ['/images/properties/property-98-1.jpg'],
    featured: false,
    type: 'House',
    description: 'An exquisitely renovated townhouse on the Upper East Side with a private garden and elevator.',
    amenities: ['Private Garden', 'Elevator', 'Chef\'s Kitchen', 'Rooftop Terrace'],
    agentId: '2',
    data_ai_hint: 'nyc townhouse'
  },
  {
    id: '99',
    title: 'West Village Carriage House',
    price: 16000000,
    address: '111 Commerce Street, New York, USA',
    bedrooms: 4,
    bathrooms: 5,
    area: 4500,
    image: '/images/properties/property-99.jpg',
    images: ['/images/properties/property-99-1.jpg'],
    featured: false,
    type: 'House',
    description: 'A rare and historic carriage house with a private garage and curb cut in the West Village.',
    amenities: ['Private Garage', 'Historic', 'Wood-Burning Fireplaces', 'Garden'],
    agentId: '3',
    data_ai_hint: 'carriage house'
  },
  {
    id: '100',
    title: 'Central Park West Penthouse',
    price: 45000000,
    address: '112 Central Park West, New York, USA',
    bedrooms: 5,
    bathrooms: 7,
    area: 7000,
    image: '/images/properties/property-100.jpg',
    images: ['/images/properties/property-100-1.jpg'],
    featured: true,
    type: 'Apartment',
    description: 'A magnificent penthouse with a wrap-around terrace overlooking Central Park.',
    amenities: ['Park Views', 'Wrap-around Terrace', 'Private Landing', 'Wood-Burning Fireplace'],
    agentId: '1',
    data_ai_hint: 'luxury penthouse'
  }
];

const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'John & Jane Doe',
    company: 'Happy Homeowners',
    comment: 'RealEstate Explorer helped us find our dream home in just a week! The process was seamless and the agents were incredibly professional. We couldn\'t be happier.',
    image: 'https://placehold.co/100x100.png',
    data_ai_hint: "happy couple"
  },
  {
    id: '2',
    name: 'Peter Jones',
    company: 'First-Time Buyer',
    comment: 'As a first-time buyer, I was nervous about the process. The team at RealEstate Explorer guided me every step of the way. Highly recommended!',
    image: 'https://placehold.co/100x100.png',
    data_ai_hint: "smiling man"
  },
  {
    id: '3',
    name: 'Mary Smith',
    company: 'Property Investor',
    comment: 'I\'ve worked with many real estate companies, but RealEstate Explorer stands out. Their market knowledge and dedication are top-notch. They helped me find a great investment property.',
    image: 'https://placehold.co/100x100.png',
    data_ai_hint: "business woman"
  },
];

const users: User[] = [
    { id: '1', firstName: 'Admin', lastName: 'User', email: 'admin@example.com', role: 'Admin', lastLogin: '2024-07-23T10:00:00Z', status: 'Active' },
    { id: '2', firstName: 'John', lastName: 'Doe', email: 'john.doe@example.com', role: 'User', lastLogin: '2024-07-22T14:30:00Z', status: 'Active' },
    { id: '3', firstName: 'Jane', lastName: 'Smith', email: 'jane.smith@example.com', role: 'User', lastLogin: '2024-07-21T11:05:00Z', status: 'Active' },
    { id: '4', firstName: 'Robert', lastName: 'Johnson', email: 'robert.j@example.com', role: 'User', lastLogin: '2024-07-20T09:15:00Z', status: 'Suspended' },
    { id: '5', firstName: 'Emily', lastName: 'Williams', email: 'emily.w@example.com', role: 'User', lastLogin: '2024-07-19T18:45:00Z', status: 'Banned' },
];


export const getProperties = async (): Promise<Property[]> => {
  return properties;
};

export const getFeaturedProperties = async (): Promise<Property[]> => {
  return properties.filter(p => p.featured);
};

export const getPropertyById = async (id: string): Promise<Property | undefined> => {
  return properties.find(p => p.id === id);
};

export const getAgents = async (): Promise<Agent[]> => {
  return agents;
};

export const getAgentById = async (id: string): Promise<Agent | undefined> => {
  return agents.find(a => a.id === id);
};

export const getTestimonials = async (): Promise<Testimonial[]> => {
  return testimonials;
};

export const getUsers = async (): Promise<User[]> => {
  return users;
};

export const getUserById = async (id: string): Promise<User | undefined> => {
  return users.find(u => u.id === id);
};
