import { BlogPostsService } from '@/services/sanity/blog-posts.sanity';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { ArrowLeft, Calendar, Tag, Cpu } from 'lucide-react';
import Link from 'next/link';
import { notFound } from 'next/navigation';

interface BlogPostPageProps {
  params: Promise<{
    slug: string;
  }>;
}

import type { Metadata } from 'next';

export async function generateMetadata({ params }: BlogPostPageProps): Promise<Metadata> {
  const post = await BlogPostsService.getPostBySlug((await params).slug);
  if (!post) return { title: 'Blog Post - Real Estate Invest' };

  return {
    title: (post.seoTitle || post.title) + ' - Real Estate Invest',
    description: post.seoDescription || post.excerpt || 'Read more on Real Estate Invest blog'
  };
}

export default async function BlogPostPage({ params }: BlogPostPageProps) {
  const { slug } = await params;

  let post: any = null;
  let relatedPosts: any[] = [];

  try {
    post = await BlogPostsService.getPostBySlug(slug);
  } catch (error) {
    console.error('Failed to fetch blog post:', error);
  }

  if (!post) {
    notFound();
  }

  try {
    // Get related posts (same category, excluding current post)
    relatedPosts = await BlogPostsService.getPostsByCategory(post.category, 3);
    relatedPosts = relatedPosts.filter(p => p._id !== post._id);
  } catch (error) {
    console.error('Failed to fetch related posts:', error);
    relatedPosts = [];
  }

  return (
    <div className="container mx-auto px-4 py-8">
      {/* Back Button */}
      <div className="mb-6">
        <Button variant="ghost" asChild className="mb-4">
          <Link href="/blog">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Blog
          </Link>
        </Button>
      </div>

      <article className="max-w-4xl mx-auto">
        {/* Post Header */}
        <header className="mb-8">
          <div className="flex items-center gap-2 mb-4">
            <Badge variant="outline">{post.category}</Badge>
            <div className="flex items-center text-sm text-muted-foreground">
              <Calendar className="w-4 h-4 mr-1" />
              {new Date(post.publishedAt).toLocaleDateString('en-US', {
                year: 'numeric',
                month: 'long',
                day: 'numeric'
              })}
            </div>
          </div>

          <h1 className="text-4xl md:text-5xl font-bold mb-4">{post.title}</h1>

          <p className="text-xl text-muted-foreground mb-6">{post.excerpt}</p>

          <div className="flex flex-wrap gap-2">
            <Tag className="w-4 h-4 text-muted-foreground" />
            {post.tags.map((tag: string) => (
              <Badge key={tag} variant="secondary">
                {tag}
              </Badge>
            ))}
          </div>
        </header>

        {/* Featured Image */}
        <div className="mb-8">
          <img
            src="/images/blog-placeholder.jpg"
            alt={post.title}
            className="w-full h-64 md:h-96 object-cover rounded-lg"
            onError={(e) => {
              e.currentTarget.src = '/images/placeholder.svg';
            }}
          />
        </div>

        {/* Post Content */}
        <div className="prose prose-lg max-w-none mb-12">
          {Array.isArray(post.content) ? (
            post.content.map((block: any, index: number) => {
              if (block._type === 'block' && block.children) {
                return (
                  <p key={index}>
                    {block.children.map((child: any) => child.text).join('')}
                  </p>
                );
              }
              return null;
            })
          ) : (
            <div dangerouslySetInnerHTML={{ __html: post.content }} />
          )}
        </div>

        {/* Post Meta */}
        <div className="border-t pt-8 mb-12">
          <div className="flex flex-wrap justify-between items-center gap-4">
            <div className="text-sm text-muted-foreground">
              {post.autoGenerated && (
                <span className="inline-flex items-center gap-1 text-xs">
                  <Cpu className="h-3 w-3" /> AI Generated • {post.source}
                </span>
              )}
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm">
                Share
              </Button>
            </div>
          </div>
        </div>
      </article>

      {/* Related Posts */}
      {relatedPosts.length > 0 && (
        <section className="max-w-4xl mx-auto">
          <h2 className="text-2xl font-bold mb-6">Related Posts</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {relatedPosts.map((relatedPost: any) => (
              <Card key={relatedPost._id} className="overflow-hidden">
                <img
                  src="/images/blog-placeholder.jpg"
                  alt={relatedPost.title}
                  className="w-full h-48 object-cover"
                  onError={(e) => {
                    e.currentTarget.src = '/images/placeholder.svg';
                  }}
                />
                <CardContent className="p-4">
                  <Badge variant="outline" className="mb-2">
                    {relatedPost.category}
                  </Badge>
                  <h3 className="font-semibold mb-2 line-clamp-2">
                    <Link
                      href={`/blog/${relatedPost.slug}`}
                      className="hover:text-primary"
                    >
                      {relatedPost.title}
                    </Link>
                  </h3>
                  <p className="text-sm text-muted-foreground line-clamp-2">
                    {relatedPost.excerpt}
                  </p>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>
      )}
    </div>
  );
}

// Generate static params for all blog posts
export async function generateStaticParams() {
  try {
    const posts = await BlogPostsService.getRecentPosts(100);
    return posts.map((post) => ({
      slug: post.slug?.current || '',
    }));
  } catch (error) {
    console.error('Failed to generate static params for blog posts:', error);
    return [];
  }
}