
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import { createClient } from '@sanity/client';

// Load environment variables from .env
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.resolve(__dirname, '../.env') });

async function debugBlogFetch() {
    console.log('🔍 Debugging Blog Data Visibility...\n');

    console.log('1. Sanity Configuration:');
    console.log(`   Project ID: ${process.env.NEXT_PUBLIC_SANITY_PROJECT_ID}`);
    console.log(`   Dataset: ${process.env.NEXT_PUBLIC_SANITY_DATASET}`);
    console.log(`   Token Present: ${!!process.env.SANITY_API_TOKEN}`);

    const client = createClient({
        projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
        dataset: process.env.NEXT_PUBLIC_SANITY_DATASET,
        useCdn: false, // Ensure fresh data
        apiVersion: '2024-01-01',
        token: process.env.SANITY_API_TOKEN,
    });

    console.log('\n2. Fetching All Posts (Raw Query):');
    try {
        // Query used in getRecentPosts
        const limit = 50;
        const query = `*[_type == "post"] | order(publishedAt desc)[0...${limit}] {
        _id,
        title,
        slug,
        excerpt,
        category,
        tags,
        publishedAt,
        autoGenerated,
        source,
        featuredImage {
          asset -> {
            url
          }
        }
      }`;

        const posts = await client.fetch(query);
        console.log(`   ✅ Query Success. Found ${posts.length} posts.`);

        const fs = await import('fs');
        const outPath = path.resolve(__dirname, '../debug_posts.json');
        fs.writeFileSync(outPath, JSON.stringify(posts, null, 2));
        console.log(`   Saved posts to ${outPath}`);

        if (posts.length > 0) {
            console.log('\n   Most Recent Post:');
            const p = posts[0];
            console.log(`   - Title: ${p.title}`);
            console.log(`   - ID: ${p._id}`);
            console.log(`   - PublishedAt: ${p.publishedAt}`);
            console.log(`   - Category: ${p.category}`);
            console.log(`   - FeaturedImage: ${p.featuredImage ? (p.featuredImage.asset ? p.featuredImage.asset.url : 'Has wrapper but no asset') : 'None'}`);
        } else {
            // Try weaker query to see if _type is wrong
            console.log('\n   ⚠️ No posts found with specific query. Trying generic query...');
            const allDocs = await client.fetch('*[_type == "post"][0...5]');
            console.log(`   Found ${allDocs.length} documents with _type == "post"`);
            if (allDocs.length > 0) {
                console.log('   Sample:', allDocs[0]);
            }
        }

    } catch (error: any) {
        console.error(`   ❌ Fetch Failed: ${error.message}`);
    }
}

debugBlogFetch().catch(console.error);
