
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

// Load environment variables from .env.local
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.resolve(__dirname, '../.env') });

import { GoogleGenerativeAI } from '@google/generative-ai';
import { createClient } from '@sanity/client';

async function verifySetup() {
    console.log('🔍 Starting Blog System Verification...\n');

    // 1. Check Environment Variables
    console.log('1. Checking Environment Variables:');

    const requiredVars = [
        'GOOGLE_AI_API_KEY',
        'NEXT_PUBLIC_SANITY_PROJECT_ID',
        'NEXT_PUBLIC_SANITY_DATASET',
        'SANITY_API_TOKEN'
    ];

    let missingVars = false;
    for (const varName of requiredVars) {
        if (process.env[varName]) {
            console.log(`   ✅ ${varName} is set`);
        } else {
            console.log(`   ❌ ${varName} is MISSING`);
            missingVars = true;
        }
    }

    if (missingVars) {
        console.error('\n❌ Verification FAILED: Missing environment variables.');
        console.error('Please check your .env.local file.');
        process.exit(1);
    }

    // 2. Verify Google Gemini Connection
    console.log('\n2. Verifying Google Gemini AI Connection:');
    try {
        // const genAI = new GoogleGenerativeAI(process.env.GOOGLE_AI_API_KEY!);
        // const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
        // const prompt = 'Say "Hello, World!" if you can hear me.';
        // const result = await model.generateContent(prompt);
        // const response = await result.response;
        // const text = response.text();
        // console.log(`   ✅ Gemini AI Responded: "${text.trim()}"`);
        console.log('   ⚠️ Skipping Gemini check to debug crash');
    } catch (error: any) {
        console.error(`   ❌ Gemini AI Connection Failed: ${error.message}`);
        // process.exit(1);
    }

    // 3. Verify Sanity Connection
    console.log('\n3. Verifying Sanity CMS Connection:');
    let client;
    try {
        client = createClient({
            projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
            dataset: process.env.NEXT_PUBLIC_SANITY_DATASET,
            useCdn: false, // We need fresh data for verification
            apiVersion: '2024-01-01',
            token: process.env.SANITY_API_TOKEN,
        });

        const result = await client.fetch('*[_type == "post"] | order(publishedAt desc)[0...1]');
        console.log(`   ✅ Sanity Connection Successful. Found ${result.length} existing posts (checking sample).`);
    } catch (error: any) {
        console.error(`   ❌ Sanity Connection Failed: ${error.message}`);
        process.exit(1);
    }

    // 4. Trigger Blog Generation (mocking the API call logic locally)
    console.log('\n4. Attempting to Generate a Test Blog Post...');
    console.log('   (This mimics the /api/generate-blog-posts logic)');

    try {
        // Generate content
        // const genAI = new GoogleGenerativeAI(process.env.GOOGLE_AI_API_KEY!);
        // const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });

        // Test article data
        const article = {
            title: "Test Article: The Future of Real Estate AI",
            description: "Artificial Intelligence is transforming how we buy and sell properties. From virtual tours to predictive pricing, the future is here.",
            source: "Verification Script"
        };

        // const prompt = `You are a blog writer. Write a short, 1-paragraph blog post about: ${article.title}. Description: ${article.description}. Return ONLY the 1 paragraph text.`;

        // const result = await model.generateContent(prompt);
        // const content = result.response.text();
        const content = "This is a test blog post content generated by the verification script (bypass AI for stability). AI is transforming real estate.";
        console.log('   ✅ Content Generated by AI (Mocked for stability)');

        // Upload an image
        console.log('   Uploading an image asset...');
        const imageRes = await fetch('https://placehold.co/600x400/png');
        if (!imageRes.ok) throw new Error('Failed to fetch placeholder image');
        const imageBuffer = await imageRes.arrayBuffer();
        // @ts-ignore
        const asset = await client.assets.upload('image', Buffer.from(imageBuffer), {
            filename: 'test-image.png'
        });
        console.log(`   ✅ Image uploaded: ${asset._id}`);

        const slug = `test-post-${Date.now()}`;
        const newPost = {
            _type: 'post',
            title: article.title,
            slug: { _type: 'slug', current: slug },
            content: [
                {
                    _type: 'block',
                    children: [{ _type: 'span', text: content }]
                }
            ],
            excerpt: content.substring(0, 100) + '...',
            category: 'real-estate',
            tags: ['test', 'ai', 'verification'],
            publishedAt: new Date().toISOString(),
            autoGenerated: true,
            source: 'verification-script',
            featuredImage: {
                _type: 'image',
                asset: {
                    _ref: asset._id
                }
            }
        };

        console.log('   Attempting to save to Sanity...');
        const savedPost = await client.create(newPost);
        console.log(`   ✅ Post Saved to Sanity! ID: ${savedPost._id}`);
        console.log(`   ✅ Verification Complete! Check http://localhost:3000/blog to see the new post.`);

    } catch (error: any) {
        console.error(`   ❌ Failed to generate/save post: ${error.message}`);
        process.exit(1);
    }
}

verifySetup().catch(console.error);
